version: '3.4'

services:
  grpcpoc.server:
    image: ${DOCKER_REGISTRY-}grpcpochybrid
    build:
      context: .
      dockerfile: GrpcPoc.Hybrid/Dockerfile

  grpcpoc.client:
    image: ${DOCKER_REGISTRY-}grpcpocclient
    build:
      context: .
      dockerfile: GrpcPoc.Client/Dockerfile

  grpcpoc.grpc:
    image: ${DOCKER_REGISTRY-}grpcpocgrpc
    build:
      context: .
      dockerfile: GrpcPoc.Grpc/Dockerfile

  grpcpoc.rest:
    image: ${DOCKER_REGISTRY-}grpcpocrest
    build:
      context: .
      dockerfile: GrpcPoc.Rest/Dockerfile
